### ISSUE TITLE
Outdated source

### ISSUE THREAD

**Issue by Hann8n** [bradleytechman/AltStore-Beginners-Guide#1]
Hi!

I’m no longer maintaining [https://hann8n.github.io/JackCracks/jackscracksaltstore.json]

I moved MovieBoxPro to its own source, and it now updates automatically.

MovieBoxPro Source:
https://hann8n.github.io/JackCracks/MovieboxPro.json

**Comment by bradleytechman** [comment]
Hi! Sorry for the late response, should be updated!
