### ISSUE TITLE
Add info to guide about automatically restarting AMDS via scheduled task

### ISSUE THREAD

**Issue by chriscorbell** [bradleytechman/AltStore-Beginners-Guide#3]
_First of all thanks for establishing this repo as a centralized source for helpful info. I have a suggestion to add the below to the readme, as I've found that the issues that are resolved by restarting AMDS happen when the service has been running for a long period of time for whatever reason. Automatically restarting the service non-interactively seems to prevent the issue from happening, I thought it may be useful to share my method for achieving this:_

For Windows users experiencing issues with wireless refreshing that are resolved by restarting Apple Mobile Device Service, you can create a batch file that contains the below:

`@echo off`
`net stop "Apple Mobile Device Service"`
`timeout /t 30`
`net start "Apple Mobile Device Service"`

You can then create a scheduled task that runs this batch file with elevated privileges (necessary for restarting services) once per day or at whatever interval you wish, this should prevent the issue entirely, as this problem seems to happen when the service has been running for a long period of time for whatever reason.

**Comment by bradleytechman** [comment]
This looks great, and sorry if i'm just being blind but what issue can be resolved?

**Comment by chriscorbell** [comment]
No worries, it’s just a suggestion for info that could be added to the guide in case someone encounters the issue of devices not seeing AltServer due to the AMDS service needing to be restarted.

**Comment by bradleytechman** [comment]
Added! Thank you!
